### ISSUE TITLE
Failed init SignClient in React Native

### ISSUE THREAD

**Issue by Kstar0722** [WalletConnect/walletconnect-monorepo#1409]
**Describe the bug**
```
{"context": "client"} this.events.getMaxListeners is not a function. (In 'this.events.getMaxListeners()', 'this.events.getMaxListeners' is undefined)
```

**Comment by xzilja** [comment]
Could you provide more info i.e. react-native version, sign-client version, is hermes enabled or disabled, anything else you can think of that will be useful when debugging this?

Did you set up v2 according to react native guides? https://docs.walletconnect.com/2.0/javascript/guides/react-native

**Comment by abdulhaseeb4239** [comment]
I am facing the same issue
These are the versions I am using
"react-native": "0.66.4",
"@walletconnect/sign-client": "^2.0.0-rc.2",

These are the steps that I did so far
1. npm install --save @walletconnect/sign-client@rc @walletconnect/react-native-compat@rc react-native-get-random-values
2. npm i text-encoding-polyfill
3. Place import 'text-encoding-polyfill' in index.js and index.ios.js
4. import “@walletconnect/react-native-compat” in App.tsx

**Comment by xzilja** [comment]
@abdulhaseeb4239 you souldn't need to install and use `text-encoding-polyfill` (unless you need it of-course). By the sound of it, it seems like `events` package doesn't get installed, however it should be there as part of "react-native-compat" install (is adds these deps for polyfilling https://www.npmjs.com/package/@walletconnect/react-native-compat) 

Can you check your package-lock file and verify that it has `events` package within it please, if not I'd try to delete node_modules and this lock file, and re-install everything fresh.

**Comment by abdulhaseeb4239** [comment]
@IljaDaderko my package-lock has the events package in it 

```
 "node_modules/events": {
      "version": "1.1.1",
      "resolved": "https://registry.npmjs.org/events/-/events-1.1.1.tgz",
      "integrity": "sha1-nr23Y1rQmccNzEwqH1AEKI6L2SQ=",
      "engines": {
        "node": ">=0.4.x"
      }
    }


"@walletconnect/react-native-compat": {
      "version": "2.0.0-rc.2",
      "resolved": "https://registry.npmjs.org/@walletconnect/react-native-compat/-/react-native-compat-2.0.0-rc.2.tgz",
      "integrity": "sha512-6inz1pyHp3PbsWDHiF5uh8vWDzQp5NEs8WMnnpmjxeN1GEznW4oQuDBjecIDtKqlOFEZgeqda3mcSBXzk9OIYg==",
      "requires": {
        "events": "3.3.0",
        "fast-text-encoding": "1.0.4"
      },
      "dependencies": {
        "events": {
          "version": "3.3.0",
          "resolved": "https://registry.npmjs.org/events/-/events-3.3.0.tgz",
          "integrity": "sha512-mQw+2fkQbALzQ7V0MY0IqdnXNOeTtP4r0lN9z7AAawCXgqea7bDii20AYrIBrFd/Hx0M2Ocz6S111CaFkUcb0Q=="
        }
      }
    },
```

    
but the events version is different in react-native-compat dependency. Can this be the issue? Btw I installed fresh couple of times but the issue persists. 
    
This is the complete error
    
 
```
 {"context": "core"} this.events.getMaxListeners is not a function. (In 'this.events.getMaxListeners()', 'this.events.getMaxListeners' is undefined)
 {"context": "client"} this.events.getMaxListeners is not a function. (In 'this.events.getMaxListeners()', 'this.events.getMaxListeners' is undefined)

```

**Comment by xzilja** [comment]
@abdulhaseeb4239 Yeh, It looks like you have 1.1.1 installed which might not have that `getMaxListeners` I'd try to do a fresh re-install like I suggested above, or perhaps try to install events package manually?

**Comment by Kstar0722** [comment]
@IljaDaderko 
"react-native": "0.65.1",
"@walletconnect/sign-client": "2.0.0-rc.2"

but I fixed problem with uninstalling `events` package

**Comment by xzilja** [comment]
Closing this issue for now, this seems to be related to events package version conflict in lock files, solvable via fresh re-install / update of lock file

**Comment by apostgit** [comment]
I still get the error with events 1.1.1 installed. Deleted the node_modules folder plus the -lock file but still get this error.

<img width="1044" alt="Screenshot 2022-11-11 at 4 44 36 PM" src="https://user-images.githubusercontent.com/54368456/201363668-5ec458f4-7992-450c-8d07-f200a35f751c.png">

I also installed the react native compat package.

**Comment by clemente-xyz** [comment]
getting the same error.

any updates guys?

**Comment by apostgit** [comment]
> getting the same error.
> 
> any updates guys?

Updating the `events` package to its latest version helped.
Run `npm i events@3.3.0`.
