### ISSUE TITLE
Authentication issues with the relay server

### ISSUE THREAD

**Issue by antondalgren** [WalletConnect/walletconnect-monorepo#1748]
**Describe the bug**
It is explained by #1733 
Creating a new issue as it seems like the previous issue has been disbanded. This is a pretty urgent and annoying issue.

```
wss://relay.walletconnect.com/?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtvenQ5MmVHVFRXSkdHcm1OOG02WThuS1RBblFxRVhSc0VwVWptYUt3MTlhMyIsInN1YiI6ImNiODY0YzUwMTRiZTVlOTBkYmU3ZmQ3ZGVhYjQwNGQ2ZWQ1ZDIwMWQxN2UxMTk5ODM0NzA4ZjNlOTBhMjA0NmEiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY3MDgzMzI0MSwiZXhwIjoxNjcwOTE5NjQxfQ.7J2Y91fWayLMZck3wrdPVKo5S0LOMERegh7jRwkO0RxvfHOoZcbcTpszaxXHU9V0dr76sMA6LCLvupON2fjMDA&projectId=e899c82be21d4acca2c8aec45e893598&ua=wc-2/js-2.1.3/androidos-chrome-108.0.0/browser:react-app.walletconnect.com
```

```HTTP Authentication failed; no valid credentials available 09:20:41.999 UTC + 1```

**To Reproduce**
1. Set your clock to 1 minute forward in the future or 24 hours + 1 minute back in history, keep your timezone unchanged.
2. Go to react-wallet.walletconnect.com

**Expected behavior**
I would expect that the server implements some kind of leeway that allows ~5 minutes ahead of time.

**Desktop (please complete the following information):**
Havent tried the reproduction steps on a desktop

**Smartphone (please complete the following information):**
 - OS: iOS/android
 - Browser Chrome

**Comment by bkrem** [comment]
@arein @heilhead could you advise here please

**Comment by heilhead** [comment]
We've just merged a fix that adds 120s leeway to both `iat` and `exp` validation. Should be deployed today, hopefully.

**Comment by arein** [comment]
@antondalgren can you please confirm whether this has been fixed for you?

**Comment by antondalgren** [comment]
@arein No, still encountering the issues on my android device.

**Comment by antondalgren** [comment]
Got it working now, thanks. Will revisit this issue if i encounter it again.
