### ISSUE TITLE
[bug] Using @web3modal/ethereum inside of pages/_app of NextJS app attempts to use react-native

### ISSUE THREAD

**Issue by arakelovd** [WalletConnect/walletconnect-monorepo#2313]
### Link to minimal reproducible example

https://codesandbox.io/p/sandbox/ve9eu2?file=%2Fpages%2F_app.tsx

### Summary

Whe using `@web3modal/ethereum` inside `pages/_app.tsx` of a NextJS app, react-native is imported.

![Screen Shot 2023-05-07 at 10 56 44 PM](https://user-images.githubusercontent.com/4978697/236724177-a0557fc6-012b-4728-aaa2-e90dede41007.png)

### List of related npm package versions

@web3modal/ethereum@^2.3.7

**Comment by arakelovd** [comment]
Also, the examples repo stops working when you regenerate the package-lock.json. https://github.com/WalletConnect/web3modal-examples/tree/main/nextjs

**Comment by xzilja** [comment]
Working on this, will transfer issue to our monorepo for sdk's as this error is coming from sign-client package

**Comment by arakelovd** [comment]
Code is found here:

https://github.com/WalletConnect/walletconnect-monorepo/blob/7a325bdbfaa2c64032f85521c515a4173560436f/providers/universal-provider/src/utils/deepLinks.ts#L39

**Comment by xzilja** [comment]
@virtuaone re example repo, was not able to replicate the issue, but all of the examples are updated to latest sdk versions now. You'll still see react-native warning which shouldn't block you from anything, this one will be sorted soon.

**Comment by Flakelf** [comment]
@0xAsimetriq got the same issue, creating WebApp using CRA + 

Why it required react-native to be installed?

"@web3modal/ethereum": "^2.4.1",
"@web3modal/react": "^2.4.1",
"ethers": "^5.7.2",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-scripts": "5.0.1",
"typescript": "^4.9.4",
"viem": "^0.3.22",
"wagmi": "^1.0.2",
"web3": "^1.9.0"

Can't build project

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/32978565/a677902a-be7c-4c69-babe-eaaf553b78df)

**Comment by ganchoradkov** [comment]
Hey, we've just released `2.7.4` and the issue should be solved

**Comment by jellohouse** [comment]
How can we update to using this version using web3modal/react and web3modal/ethereum node modules?

**Comment by jellohouse** [comment]
I'm still getting the same issue after updating to the latest @web3modal/ethereum @web3modal/react wagmi viem versions.

**Comment by mr-new-0509** [comment]
> Hey, we've just released `2.7.4` and the issue should be solved

Solved?
Which modules should I upgrade to 2.7.4?

**Comment by ganchoradkov** [comment]
@jellohouse it will take a day or so for the update to roll out in wagmi/web3modal. Additionally, if you're using npm/yarn as package managers, you can explicitly define `"@walletconnect/ethereum-provider": "2.7.4"` in your `package.json`. This should take priority and might solve the issue while waiting for wagmi release

@mr-new-0509 if you're using `@walletconnect` packages - sign/ethereum/universal providers the update is immediately available with v`2.7.4`

**Comment by mr-new-0509** [comment]
Wagmi released `v1.0.5` 2 days ago.
`npm install wagmi@1.0.5`
It will be working.

**Comment by bmeeder22** [comment]
I am also still getting this issue even after explicitly upgrading to "@walletconnect/ethereum-provider": "2.7.4"

Problem with upgrading wagmi is that 1.0.5 introduces an insane amount of breaking changes.

**Comment by mr-new-0509** [comment]
> I am also still getting this issue even after explicitly upgrading to "@walletconnect/ethereum-provider": "2.7.4"
> 
> Problem with upgrading wagmi is that 1.0.5 introduces an insane amount of breaking changes.

No big difference between wagmi 1.0.2 and 1.0.5.
I faced `Module not found: Cannot resolve "react-native" error` when I used `wagmi 1.0.2`.
But after upgrading the wagmi into `1.0.5`, the error was fixed.
After the upgrading, I didn't change any code that I developed when I use `1.0.2`.

**Comment by paintoshi** [comment]
Upgrading to 1.0.5 solved this issue for me too. No breaking changes from 1.0.2.

**Comment by happywomwom-wombat** [comment]
> I am also still getting this issue even after explicitly upgrading to "@walletconnect/ethereum-provider": "2.7.4"
> 
> Problem with upgrading wagmi is that 1.0.5 introduces an insane amount of breaking changes.

Did you fix it with wagmi v0?
