### ISSUE TITLE
provider.enable Doesn't Resolve

### ISSUE THREAD

**Issue by lnbc1QWFyb24** [WalletConnect/walletconnect-monorepo#243]
Calling `provider.enable` to show the QR modal works, but if the user closes the modal by clicking the cross and then `provider.enable` is called again, the QR modal doesn't render and the promise never resolves.

Version `1.0.0-beta.47`

This code can be run to replicate the issue: 

```javascript
import WalletConnectProvider from "@walletconnect/web3-provider";
  
const provider = new WalletConnectProvider({
  infuraId: '<INFURA_ID>'
});

async function run() {
  console.log("calling enable first time");

  await provider
    .enable()
    .then(() => console.log("first call resolved"))
    .catch(() => console.log("first call error"));

  console.log("calling enable second time");

  await provider
    .enable()
    .then(() => console.log("second call resolved"))
    .catch(() => console.log("second call error"));
 }

run()

// -> calling enable first time
// -> first call error
// -> calling enable second time
```

**Comment by pedrouid** [comment]
Interesting edge case, I've never seen this one before. Thanks for reporting 🙏 I will try to get a fix soon.

**Comment by lnbc1QWFyb24** [comment]
Hey @pedrouid just checking in to see if have you made any progress on this one? 😄

**Comment by pedrouid** [comment]
Fixed! Please update to latest

**Comment by lnbc1QWFyb24** [comment]
Awesome! Thanks mate

**Comment by lnbc1QWFyb24** [comment]
Hey @pedrouid I just tested this with version `1.0.13` and I am still seeing the same behavior. Did you test with the above sample code with that version and see that is was fixed?

**Comment by Enigmatic331** [comment]
Any chance you had any progress on this so far @aaronbarnardsound? Seems that I am having the same issue as well, on /@walletconnect/web3-provider@1.2.2.

**Comment by lnbc1QWFyb24** [comment]
@Enigmatic331 Unfortunately not, still seeing this issue

**Comment by Enigmatic331** [comment]
Ah....

Here at Etherscan we will be working around this by putting in a try-catch and refreshing the iframe which the writeContract loads from. Unfortunately we will not be able to do it to the dApp page as it'd be bad UX to force the entire page to reload.

**Comment by taylorjdawson** [comment]
@pedrouid [This demo](https://codesandbox.io/s/wallet-connect-qr-bug-demo-itwcg) illustrates that this bug persists and the issue should be re-opened

**Comment by Shirikatsu** [comment]
I'm also suffering from the same issue still persisting on `@walletconnect/web3-provider: "^1.4.1"`.

**Comment by jeromevvb** [comment]
The issue still persist.

**Comment by taylorjdawson** [comment]
@pedrouid Bump

**Comment by taylorjdawson** [comment]
@pedrouid Will this be fixed in v2?

**Comment by MrPeanutz** [comment]
Same issue going on here

**Comment by MrPeanutz** [comment]
Please reopen this issue @pedrouid

**Comment by juampibermani** [comment]
Same issue here, maybe while you are fixing it you could hide the button

**Comment by AmmarKhalid123** [comment]
Facing same issue, please re-open the issue

**Comment by Loque18** [comment]
same issue

**Comment by antinomy-studio** [comment]
Having the same issue. This needs to be reopen. cc @pedrouid

**Comment by avivash** [comment]
Hey all, I came up with a workaround for this issue until it gets fixed by the walletconnect team. Hopefully it helps, it seems to work consistently 👍🏼 https://github.com/WalletConnect/walletconnect-monorepo/issues/747#issuecomment-1137952645

**Comment by movassagh** [comment]
I am still facing the same problem

**Comment by aximas** [comment]
And I am still facing the same problem
Somebody know how resolve it ?

**Comment by evgecoder** [comment]
Just create new class instance and try provider.enable() again....

const provider = new WalletConnectProvider();
provider.enable();

It's one way to solve this.
