### ISSUE TITLE
Uncaught Error: No matching key.

### ISSUE THREAD

**Issue by ramvi** [WalletConnect/walletconnect-monorepo#3334]
### Discussed in https://github.com/orgs/WalletConnect/discussions/2728

<div type='discussions-op-text'>

<sup>Originally posted by **kartikchoubisa** June 22, 2023</sup>
Hi, I am using the react wallet chat demo available [here](https://github.com/WalletConnect/web-examples/tree/main/wallets/react-wallet-chat).

```
_app-3a3aeafdf4ce7f98.js:1 Uncaught (in promise) Error: No matching key. history: 1687441832453713
    at ic.getRecord (_app-3a3aeafdf4ce7f98.js:1:2771673)
    at ic.get (_app-3a3aeafdf4ce7f98.js:1:2770296)
    at nc.onRelayEventResponse (_app-3a3aeafdf4ce7f98.js:1:2765592)
    at o.<anonymous> (_app-3a3aeafdf4ce7f98.js:1:2768494)
```

Everytime I send a message, I get multiple of these errors. 
I implemented chat on my own using the docs, I get the same error.

What are the consequences of this? I see that sometimes messages are lost, could this error be the reason?

Thanks!

Detailed log:
```
_app-3a3aeafdf4ce7f98.js:1 Uncaught (in promise) Error: No matching key. keychain: d046a7a0e253bcf2d55833288c57776610c2cb1631804916262289dc6b592044
    at Hr.get (_app-3a3aeafdf4ce7f98.js:1:2641789)
    at Kr.getSymKey (_app-3a3aeafdf4ce7f98.js:1:2644858)
    at Kr.decode (_app-3a3aeafdf4ce7f98.js:1:2643924)
    at o.<anonymous> (_app-3a3aeafdf4ce7f98.js:1:2673258)
    at o.emit (_app-3a3aeafdf4ce7f98.js:1:1305028)
    at fn.onMessageEvent (_app-3a3aeafdf4ce7f98.js:1:2662453)
    at async fn.onProviderPayload (_app-3a3aeafdf4ce7f98.js:1:2662312)
Hr.get @ _app-3a3aeafdf4ce7f98.js:1
getSymKey @ _app-3a3aeafdf4ce7f98.js:1
Kr.decode @ _app-3a3aeafdf4ce7f98.js:1
(anonymous) @ _app-3a3aeafdf4ce7f98.js:1
o.emit @ _app-3a3aeafdf4ce7f98.js:1
onMessageEvent @ _app-3a3aeafdf4ce7f98.js:1
await in onMessageEvent (async)
o.emit @ _app-3a3aeafdf4ce7f98.js:1
onMessageEvent @ _app-3a3aeafdf4ce7f98.js:1
await in onMessageEvent (async)
onProviderPayload @ _app-3a3aeafdf4ce7f98.js:1
await in onProviderPayload (async)
(anonymous) @ _app-3a3aeafdf4ce7f98.js:1
o.emit @ _app-3a3aeafdf4ce7f98.js:1
onPayload @ _app-3a3aeafdf4ce7f98.js:1
(anonymous) @ _app-3a3aeafdf4ce7f98.js:1
o.emit @ _app-3a3aeafdf4ce7f98.js:1
onPayload @ _app-3a3aeafdf4ce7f98.js:1
e.onmessage @ _app-3a3aeafdf4ce7f98.js:1
_app-3a3aeafdf4ce7f98.js:1 Uncaught (in promise) Error: No matching key. history: 1687442077122389
    at ic.getRecord (_app-3a3aeafdf4ce7f98.js:1:2771673)
    at ic.get (_app-3a3aeafdf4ce7f98.js:1:2770296)
    at nc.onRelayEventResponse (_app-3a3aeafdf4ce7f98.js:1:2765592)
    at o.<anonymous> (_app-3a3aeafdf4ce7f98.js:1:2768494)
getRecord @ _app-3a3aeafdf4ce7f98.js:1
get @ _app-3a3aeafdf4ce7f98.js:1
onRelayEventResponse @ _app-3a3aeafdf4ce7f98.js:1
(anonymous) @ _app-3a3aeafdf4ce7f98.js:1
await in (anonymous) (async)
(anonymous) @ _app-3a3aeafdf4ce7f98.js:1
await in (anonymous) (async)
o.emit @ _app-3a3aeafdf4ce7f98.js:1
onMessageEvent @ _app-3a3aeafdf4ce7f98.js:1
await in onMessageEvent (async)
onProviderPayload @ _app-3a3aeafdf4ce7f98.js:1
await in onProviderPayload (async)
(anonymous) @ _app-3a3aeafdf4ce7f98.js:1
o.emit @ _app-3a3aeafdf4ce7f98.js:1
onPayload @ _app-3a3aeafdf4ce7f98.js:1
(anonymous) @ _app-3a3aeafdf4ce7f98.js:1
o.emit @ _app-3a3aeafdf4ce7f98.js:1
onPayload @ _app-3a3aeafdf4ce7f98.js:1
e.onmessage @ _app-3a3aeafdf4ce7f98.js:1
_app-3a3aeafdf4ce7f98.js:1 Uncaught (in promise) Error: No matching key. history: 1687442077122389
    at ic.getRecord (_app-3a3aeafdf4ce7f98.js:1:2771673)
    at ic.get (_app-3a3aeafdf4ce7f98.js:1:2770296)
    at Dp.onRelayEventResponse (_app-3a3aeafdf4ce7f98.js:1:2892789)
    at o.<anonymous> (_app-3a3aeafdf4ce7f98.js:1:2897913)
getRecord @ _app-3a3aeafdf4ce7f98.js:1
get @ _app-3a3aeafdf4ce7f98.js:1
Dp.onRelayEventResponse @ _app-3a3aeafdf4ce7f98.js:1
(anonymous) @ _app-3a3aeafdf4ce7f98.js:1
await in (anonymous) (async)
(anonymous) @ _app-3a3aeafdf4ce7f98.js:1
await in (anonymous) (async)
o.emit @ _app-3a3aeafdf4ce7f98.js:1
onMessageEvent @ _app-3a3aeafdf4ce7f98.js:1
await in onMessageEvent (async)
onProviderPayload @ _app-3a3aeafdf4ce7f98.js:1
await in onProviderPayload (async)
(anonymous) @ _app-3a3aeafdf4ce7f98.js:1
o.emit @ _app-3a3aeafdf4ce7f98.js:1
onPayload @ _app-3a3aeafdf4ce7f98.js:1
(anonymous) @ _app-3a3aeafdf4ce7f98.js:1
o.emit @ _app-3a3aeafdf4ce7f98.js:1
onPayload @ _app-3a3aeafdf4ce7f98.js:1
e.onmessage @ _app-3a3aeafdf4ce7f98.js:1

```

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/55321327/335c3516-3d50-4365-bb8a-322d7786e8d7)
</div>

**Comment by ramvi** [comment]
I noticed that the discussion was not going anywhere, which isn't that strange as it wasn't posed as an issue. Now it can be fixed :)

**Comment by ganchoradkov** [comment]
Hey @ramvi, we just published `2.9.2` and these errors should no longer be unhandled. 
Please update to latest and retry again

**Comment by ramvi** [comment]
Hi @ganchoradkov,

I've just upgraded to version 2.9.2, as you suggested, but I'm still encountering the same error.

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/877417/c3327172-468b-4445-94fa-d50b057ffb35)
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/877417/652798d6-6875-4e4a-908b-c2b7bf67c2a0)

**Comment by ramvi** [comment]
When I comment out the session restore, the error doesn't occur, and everything runs smoothly. Could this be related to the underlying issue? Looking forward to your guidance. Thanks!

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/877417/d6b46523-3a20-403a-bf21-e0278de3dc5a)

**Comment by ganchoradkov** [comment]
What is this session restore that you're mentioning? Custom logic? 
Custom logic shouldn't cause such behaviour unless it makes somehow event listeners to be subscribed twice

**Comment by ramvi** [comment]
[It's from the docs](https://docs.walletconnect.com/2.0/web/sign/dapp-usage#restoring-a-session)

**Comment by MickaelNeves** [comment]
Im using RainbowKit v^1.0.6 + WalletConnect v2 + Argent Wallet and I cant verify a signature 
![Screenshot 2023-08-02 at 11 04 31](https://github.com/WalletConnect/walletconnect-monorepo/assets/20476271/ae119fe2-5a04-4469-8f6a-bc2c8a81b7ab)

**Comment by ganchoradkov** [comment]
@ramvi, could you share the steps to reproduce? i.e. which wallet are you using & the actions to achieve the error? 
I tried on my own but failed to reproduce

**Comment by ramvi** [comment]
Hi @ganchoradkov,

Thank you for your attention to this issue. I'd like to clarify the steps to reproduce the error in my scenario:

1. I've built a simple wallet using ethers and WalletConnect (WC) SignClient.
2. I connect a sample dapp with the app using WC and make a request to the app, i.e., "Do you want to store this verifiable credential (VC)?"
3. I then navigate to another site on the server, which represents another dapp, and connect with the same app, making a request, i.e., "Do you want to share the VC?"
4. Upon clicking accept, I immediately encounter the error "No matching key."

Interestingly, the process does work, and the request goes through, despite the error. Furthermore, when I commented out the session restore, the flow worked without the error being thrown. This indicates that the session restoration may be related to the underlying issue.

I hope this provides enough information to assist in diagnosing the problem. Please let me know if there's anything else you need.

**Comment by ganchoradkov** [comment]
Recently we published a patch where `no matching key: keychain` should no longer happen.

>Interestingly, the process does work, and the request goes through, despite the error

regarding the `no matching key: history` its usually a non-blocking error as it's caused when the SDK receives a message twice. i.e. the first payload is processed normally, while the second (duplicate) throws. We're still ironing out v2 behavior,
so feel free to disregard the `no matching key: history`. 

I'm going to go ahead and close this issue as there seems no new `loss of messages` or `blocking` errors happening. Feel free to open it again/or create a new one if you experience SDK usage disruption 💯

**Comment by Arthurgallina1** [comment]
@ganchoradkov 
I'm using latest version and still getting ``no matching key: `` on many situations.

When trying to disconnect, sometimes when there's a request proposal. 
By the logs I see sometimes WC is trying to use a old key/topic that it recovered from local storage but is not active anymore.

It throws errors and can't be caught, what is the suggest workaround?

**Comment by PetromirDev** [comment]
In my case this issue was sometimes happening on disconnect. The way I resolved it is:
```
try {
  await web3wallet.disconnectSession({
    topic,
    reason: getSdkError('USER_DISCONNECTED')
  })
} catch (e) {
  if (e?.message?.includes('No matching key. keychain')) {
    try {
      await web3wallet.engine.signClient.session.delete(topic, 'USER_DISCONNECTED')
    } catch {
      // Do something here
    }
  }
}
```
