### ISSUE TITLE
WalletConnect v2 subscriptions storage issue leading to freeze/crash

### ISSUE THREAD

**Issue by jeanregisser** [WalletConnect/walletconnect-monorepo#625]
Hey,

We discovered a problem with WalletConnect v2 stored subscriptions leading to a freeze/crash.
Unfortunately we haven't yet pinpointed the exact steps to reproduce this, however we've gathered some data about what's happening.

# Problem

We initially spotted the issue in our [Valora wallet](https://github.com/valora-inc/wallet). See https://github.com/valora-inc/wallet/issues/1215.
But then noticed it's happening on the test web app we use too: https://use-contractkit-c-labs.vercel.app/

Approximate repro steps on the web app:
1. Go to https://use-contractkit-c-labs.vercel.app/
2. Tap Connect
3. Scan the QR code with Valora (note that we've remotely disabled WC v2 in the production versions of Valora because of this issue)
4. Sign some things (not sure it's needed though) 
5. Let the tab open for a while
6. Refresh it, it will eventually crash

This is happening with `@walletconnect/client` `2.0.0-beta.18`.

The main problem is a huge number of subscriptions end up being stored in local storage (8000+).
Once the client tries to restore them in a `Promise.all` call when initializing, it blows up (Chrome page errors, mobile app crashes, running out of memory). https://github.com/WalletConnect/walletconnect-monorepo/blob/56db6e088d55146249788b8a27dfb9609f5f297b/packages/client/src/controllers/relayer.ts#L291-L300

# Data

Here's the data causing this (took some screenshots, but I can provide the raw data too).

You can see it's storing 8000+ subscriptions for basically 2 different topics:
<img width="1785" alt="Screenshot 2021-10-19 at 09 38 57" src="https://user-images.githubusercontent.com/57791/137872901-c02c10be-7362-4a35-bb50-c070c763b9f7.png">

<details>
<summary>And here are the other parts of the stored state that may be of interest.</summary>
<img width="1785" alt="Screenshot 2021-10-19 at 09 39 11" src="https://user-images.githubusercontent.com/57791/137873217-cb82e677-1d0a-460d-a30c-7da69b0b6112.png">
<img width="1785" alt="Screenshot 2021-10-19 at 09 39 16" src="https://user-images.githubusercontent.com/57791/137873240-1d87275b-88e1-4544-b47c-597c59400638.png">
<img width="1785" alt="Screenshot 2021-10-19 at 09 39 19" src="https://user-images.githubusercontent.com/57791/137873288-293aebeb-90df-41d7-9308-1b6e349c4bea.png">
<img width="1785" alt="Screenshot 2021-10-19 at 09 39 22" src="https://user-images.githubusercontent.com/57791/137873320-9656597e-09b9-4976-99ce-6b97270aa4eb.png">
<img width="1785" alt="Screenshot 2021-10-19 at 09 39 31" src="https://user-images.githubusercontent.com/57791/137873389-9feb2fe0-2c31-424f-b106-19bf3bbaabac.png">
</details>

I've also been able to capture the [logs of Valora with WalletConnect logger in `trace` mode](https://github.com/WalletConnect/walletconnect-monorepo/files/7371609/Valora.WC-v2.init.issue.logs.txt).

Note that there's a misleading log statement:
```
[Fri Oct 15 2021 15:47:18.275]  DEBUG    {"context": "client"} [{"context": "client/relayer"}, {"context": "client/relayer/subscription"}, "Successfully Restored subscriptions for relayer subscription"]
[Fri Oct 15 2021 15:47:18.281]  TRACE    {"context": "client"} {"context": "client/relayer"} {"context": "client/relayer/subscription"} {"method": "restore", "subscriptions": [], "type": "method"}
```
It says the subscriptions are empty when it was actually 8000+ items. Not sure why it doesn't display them.

Let me know if you need any other info.

Thanks!

**Comment by jeanregisser** [comment]
Ah I just saw https://github.com/WalletConnect/walletconnect-monorepo/commit/b858786ac9d36d5637e8e02ce39fde90e4d04d19 likely fixes the issue observed!

We're gonna update to `2.0.0-beta.19` and report back.

**Comment by jeanregisser** [comment]
The problem can be reproduced with `2.0.0-beta.19` 😢 

Using https://react-app.walletconnect.org/ (it's using  `2.0.0-beta.19`, right?) and a local build of Valora where I updated to `2.0.0-beta.19`.

<img width="1733" alt="Screenshot 2021-10-19 at 14 01 49" src="https://user-images.githubusercontent.com/57791/137905903-3c511eae-3594-46db-8504-93b7aecedea6.png">
<img width="1733" alt="Screenshot 2021-10-19 at 14 06 58" src="https://user-images.githubusercontent.com/57791/137906056-cfed7cfe-c2e9-4d53-a588-006c4fec4019.png">

Still a bit unsure of the exact steps, what I describe above still applies, but I also let the computer sleep and after I came back I directly saw the issue.
This seems to indicate the WalletConnect client reconnection logic may lead to this issue.

**Comment by pedrouid** [comment]
hi @jeanregisser, so I've published a canary release to tackle this but because I'm struggling to reproduce it properly for testing I would appreciate if you could test it on your side

you can install the canary as follows
```
npm install --save @walletconnect/client@canary

OR

yarn add @walletconnect/client@canary
```

Additionally I made it easier to support v1.0 in parallel without using NPM aliases
```
npm install --save @walletconnect/legacy-client@canary

OR

yarn add @walletconnect/legacy-client@canary
```

Let me know what you find on your end 🙏

**Comment by pedrouid** [comment]
Just published another canary release to fix a dependency issue with the legacy-client. 

Please try the latest canary release (2.0.0-beta.20.2) 🙌

**Comment by GHChrisSu** [comment]
We tried beta.20.3 still have this issue, but not usual. When I was update wallet connect from beta.14 to beta.20.3 this issue will happen. The wallet or dapp already linked case.

**Comment by pedrouid** [comment]
I just published another canary release last night which I feel more confident about tackling this issue.

version 2.0.0-beta.20.5

It's a hard bug to reproduce consistently which is making it significantly harder to fix without a proper test that I can follow 

That being said... there are some breaking API changes on the initialization parameters to consider for beta.20.4

Please let me know any feedback on this

**Comment by GHChrisSu** [comment]
Still have this bug at beta 20.5

**Comment by mrosendin** [comment]
@GHChrisSu try upgrading to beta 21. I just did, and the issue has disappeared...*knocks on wood*

**Comment by chadyj** [comment]
@jeanregisser Was your issue fixed in beta 21?

**Comment by GHChrisSu** [comment]
Not fix yet, likely way to reproduce scene is make computer in sleep mode for one night, when I get up open my computer and then open the wallet and it already crashed. This scene happened three times. Seems like sleep computer for a while will reproduce.

**Comment by GHChrisSu** [comment]
Is there any way to detect this when issue happen and I can clear the local storage, cause every time this happened I clear the local storage it can work again

**Comment by alejomendoza** [comment]
Any updates on this one?

**Comment by kverushi** [comment]
Any updates on this?

**Comment by dfordivam** [comment]
I have also observed this issue consistently and also observed that it happens much more likely if the browser is running on a laptop (slower) machine. And the relay server connection reset (due to 502) triggers a series of events which tends to blow up the subscriptions count.

**Comment by chadyj** [comment]
The team published a new release that addresses this issue. 

https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.0.0-beta.24

We would love your feedback to confirm the fix!

**Comment by pedrouid** [comment]
We had to push some fixes on top of the last release 

Please use beta.26 instead 

https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.0.0-beta.26

**Comment by dfordivam** [comment]
Thanks for the new release addressing this issue. I tried the beta.26 release, containing the fix mentioned in this comment  (https://github.com/WalletConnect/walletconnect-monorepo/issues/548#issuecomment-1085792067), to make sure the app does not crash due to websocket error, and observed that after about 12 hours the browser tab was working fine on my desktop machine, ~~but unfortunately it did crash on my laptop machine.
So the severity of this issue has reduced, but would needs further fixes and improvements.~~  (Edit: it was mistake in my test setup)
I will run the experiment again and let you know if I find anything interesting.

**Comment by dfordivam** [comment]
Update on testing of the latest release (2.0.0-beta.26), I kept the browser tab in idle for more than two days and so far things look good, the CPU usage is normal and the tab did not crash.

**Comment by chadyj** [comment]
Thanks for testing @dfordivam 🙌

**Comment by dfordivam** [comment]
Update 2: I did further testing on Monday, this time the wallet-connect was not idle. I did >10 requests in a day, and put the laptop on sleep (4 times) during the day. During night the laptop was ON. The next day both Firefox and Chrome tabs crashed.

I refreshed the Firefox tab, and after about 5 min of high CPU usage it became responsive. The relayer:subscription count is 16825. On Chrome it opened faster, the relayer:subscription count is 8474.
